const GET_WEATHER_BY_ZIPCODES_SAGA = 'app/weather/GET_WEATHER_BY_ZIPCODES_SAGA';
const SET_WEATHER_DATA = 'app/weather/SET_WEATHER_DATA';

export {
  GET_WEATHER_BY_ZIPCODES_SAGA,
  SET_WEATHER_DATA,
};
